### ISSUE TITLE
Are ACLs respected on class-based resources?

### ISSUE THREAD

**Issue by tdavis** [Cornices/cornice#120]
This is more of a question than an issue as I couldn't readily find the answer. If I define a resource using the class and define an `__acl__` attribute, will it be used as it would in a normal Pyramid app?

**Comment by robvdl** [comment]
The problem I see, is that regular pyramid views use the list of ACLs defined on the RootFactory class, however cornice doesn't seem to use this at all and require it's own callback to build the list of ACLs, even though the RootFactory class is already called for every request, which I found a bit strange.

I tried to make a callable that just returned request.context.__acl__ so the ACLs defined in the RootFactory class that are used by the rest of the Pyramid application can be used by cornice resources too.  The problem however is that the request object seems to be missing request.context property in a cornice ACL callable, yet everywhere else in the Pyramid application it is present.  Not sure if Cornice "strips" some properties of the request object or not.

Anyway, my solution was as follows:

```python
from myapp.security import RootFactory

def get_global_acls(request):
    # even though we have to construct RootFactory again (which seems silly),
    # it only actually seems to be calling it once this way for API resources, which is fine.
    return RootFactory(request).__acl__

@resource(acl=get_global_acls)
class SomeApi(object):
    pass
```

**Comment by DaineDanielson** [comment]
I think there is a fundamental mismatch between the way Cornice treats ACLs and the way Pyramid maintainers envision them being used.

I am trying to implement this 'official' Pyramid ACL design pattern:
http://docs.pylonsproject.org/projects/pyramid/en/latest/tutorials/wiki2/authorization.html#add-resources-and-acls

Cornice does not play nice with this Pylons-sanctioned--dare I say, recommended--pattern.

It looks like @sbbowers is also trying to apply this pattern in #100 [here](https://github.com/Cornices/cornice/issues/100#issuecomment-32888146).
He succeeds because his ACL is static, but his solution fails for dynamic ACL methods like `PageResource.__acl__(self)` from the Pylons example above.

A 'dynamic' ACL method is an ACL callable that uses an argument `self`.From Pylons:

**Comment by leplatrem** [comment]
Thanks a lot for this detailed feedback.

I totally agree with you, there is no reason for Cornice to have its own pattern. 

Now, I can't really promise anything regarding this refactoring. Cornice is not on top of my maintenance duties. But if you are willing to help fixing this, I would be very happy to help test or review your contributions :) 

Thanks again!

**Comment by robvdl** [comment]
Hi I am in the same boat myself when it comes to time sorry.  I have so many other projects going, at the time I was using Cornice for a project at work but they are still stuck on 1.0 and they have no plans to upgrade and have no real bau budget yet (typical clients) and I have since moved to another team doing more Django than Pyramid again.

**Comment by wjehenddher** [comment]
Interesting discussion about it (including a potential solution/workaround) 

Cornices/cornice/issues/322

**Comment by leplatrem** [comment]
Please checkout current master ( f864fae ) with the new design! Thanks @wjehenddher for your efforts, and thanks everyone for your patience on this ;)
