### ISSUE TITLE
Problem when using @resource wrapper

### ISSUE THREAD

**Issue by nightmarebadger** [Cornices/cornice#259]
If you build a service "by hand", with which I mean something like:

```
users = Service(name='users', path='/users', description="Users")
_USERS = {}
def get_users(request):
    """Returns a list of all users."""
    return {'users': _USERS.keys()}
```

and then look at it's `service.definitions`, the second item in the information is the **function itself**. 

If you build a service by using the `@resource` wrapper, so something like:

```
@resource(collection_path='/user', path='/user/{name}')
class UserView(object):
    """Service for users."""

    def __init__(self, request):
        self.request = request

    @view(renderer='json')
    def get(self):
        """Returns a user."""
        return {'user': ' '}
```

and then look at it's `service.definitions`, the second item in the information is not the function, but **it's name** (a string). 

I'm guessing this could cause problems in more then one place, but I noticed it when trying out the SPORE view, where the descriptions were 

```
str(object='') -> string\n\nReturn a nice string representation of the object.\nIf the argument is a string, the return value is the same object.
```

instead of the actual doctring (the output is of course the docstring of a string object). 

I've 'hunted down' the problem to `resource.py` (https://github.com/mozilla-services/cornice/blob/master/cornice/resource.py#L62-L67), where it pushes `view_attr` (the name of the view) instead of the actual method.

Obviously pushing the actual method can (and a quick test shows that it does) break other things (the functionality at least, maybe something more), so what's the best solution? Check for a string in spore.py and go for the class method docstring there? What about the other places where this problem (possibly, didn't test to see if it's a problem anywhere else) occurs?

**Comment by hamx0r** [comment]
I'm seeing the same in the currently-undocumented swagger.py included with cornice 0.17.

**Comment by ametaireau** [comment]
Thanks for taking a look at that. I believe the best solution here is to update the code of `spore.py` to do type checking on a string and get the docstring if it is a string. This way we don't break any compatibility and we make it work.

`swagger.py` shouldn't have been pushed here so I'll remove it ASAP, as it's neither finished nor working.

About the issue we're discussing here, I believe we should try to be consistent in the type of what we're passing in `view_attr`, that's correct.

The whole `resource.py` file is built against the concept of decorators, which sometimes makes things hard to understand / debug. It was also the case for the first version of Cornice.

I'm not sure what the future is for this `resource.py` but I would like to deprecate it in favor of a better way to define resources without using decorators (e.g. you should extend a base class and `register` it within cornice (which will use pyramid internally).

We don't have yet this implemented, but we want to have it soon for [cliquet](https://github.com/mozilla-services/cliquet) and plans are to directly include it in cornice afterwards.

Thoughts?

**Comment by hamx0r** [comment]
Thank you for the feedback.  Can we branch this discussion so the spore.py discussion happens her and the swagger.py discussion happens elsewhere?  I see that the swagger.py which shipped with cornice 0.17 used some of the same code as spore.py, which caused me to see the same problem as @nightmarebadger who was using spore.  

Moving forward with swagger.py": my company project is making use of cornice 0.17 and we're using `@resource` for all our resources ("paths" in swagger speak).  I have put effort into revising swagger.py in our local environment to be 2.0 compatible instead of 1.2 (which was the aim of 0.17's swagger.py).  I would be very happy to contribute to the development of the cornice swagger module.  Is there a dev branch i can help with here?   Has there been design discussion on swagger.py so I can implement in a particular way?

## Proposed implementation
So far I have been running forward like so (_italics_ mean it's a Swagger term, and `code` means it's python):
Our swagger.py has a modified `generate_swagger_spec()` and some decorators.  Essentially, we can add data to the swagger document: `@swagger.path` at the _path_ level, and `@swagger.operation' at the _operation_ level.  These hooks to add swagger data would merge with data harvested by introspection (ie  _summary_ comes from each resource method's `__doc__`).   

The swagger spec offers globals (ie [_path-level parameters_](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-4) which can be defined, implying every _operation_ in that _path_ requires the same parameters.  Per the linked doc, such _parameters_ can be overwritten, but not removed from the list of required parameters of all the _operations_ which inherit them.    Using this same rule of overwriting, we can can use this design for swagger.py:
1. The new signature will be `generate_swagger_spec(services, title, version, **kwargs)`
  * These args are the _Required_ fields for a [_Swagger Object_](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#swagger-object)
  * `**kwargs` can supply any other _Swagger Object_ parameter by name (_host_, _parameters_, etc)
2. Swagger data will be acquired in two ways:
  * Introspection of cornice and pyramid related code
    - _path_ parameters come from `cornice.service.path`
    - _operation_ key values (get, put, etc) in a [_Path Item Object_](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#path-item-object) come from `cornice.service.definitions`
  * Addition using the decorators
    - `@swagger.path` takes `**kwargs` which map to [_Pattern Item Object_](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#path-item-object) values (only _parameters_ are useful I think)
    - `@swagger.operations` takes `**kwargs` which will map completely to [_Operation Object_](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operationObject)
3. Overwrite rule:
  * Introspection-harvested data happens first
  * Added (decorated) data gets used to add/overwrite (using `dict.udpate`)


## Example
### Decorated Resources
Such a resource would be found with `pyramid.config.scan()`
```python
from my_swagger_models import parameter_definitions
@resource(collection_path='/tokens', path='/tokens/{id}')
@swagger.path(parameters=parameter_definitions)
class Token(object):
    """A token is an object of my appreciation"""
    def __init__(self, request):
        self.request = request

    # This method implements the GET /tokens/<id> http call.
    def get(self):
        """What what you got"""
...
   # This method implements the POST /tokens http call.
   # These Swagger       **kwargs map directly to Operation Object Definitions
    @swagger.operation(parameters=[{'name': 'X-OpenAM-Username', 'in': 'header', 'description': 'LDAP Username'},
                                       {'name': 'X-OpenAM-Password', 'in': 'header', 'description': 'LDAP Password'}])
    def collection_post(self):
...
```


### The View
```python
# We can store our global details elsewhere, or maybe generate them from some other plugin to get a swagger-compliant nested dictionary
from my_swagger_models import parameters, responses

@view_config(route_name='swagger_json', renderer='json', )
def swagger_json(request):
    '''Swagger spec in JSON form'''
    services = service.get_services()
    # We can even define swagger compliant dictionaries for any other Swagger Object item
    info = {'title': 'NMS API', 'version': '1.0', 'contact': {
        'name': 'Hamx0r',
        'email': 'hamx0r@github.com'}
        }

    return generate_swagger_spec(services, info['title'], info['version'], info=info, parameters=parameters, responses=responses)
```

What do you think?  My goal is to offload documentation to the well-maintained swagger spec documentation by keeping a 1:1 mapping off terminology and structure (which works great since nested Python dicts/lists look very  JSONic).  Also, it allow creative uses of the decorators by users who may want to override or add documentation notes, or compile such notes by introspecting other code they may be using (ie cliquet).

**Comment by ametaireau** [comment]
Hi, thanks for the response.

The `swagger.py` file was just me playing with it but it actually never was released, and I discontinued my efforts on it. I put together a gist with what I had in this local branch: https://gist.github.com/ametaireau/34058059abc3a5a93950

Now, onto the actual proposal.

Ideally, you wouldn't need to add decorators to add information for swagger, since everything should be known by the Service class.

In case it's not enough, then I believe adding the extra bits of information directly with the cornice decorators should be enough (e.g. no need to define a new decorator type).

Alternatively, having specific decorators could be handly, but I feel it would introduce yet another decorator into the mix.

@leplatrem @Natim thoughts?

**Comment by hamx0r** [comment]
Thanks.  I'd also prefer to get everything by introspection if possible.  This is my first pyramid (and cornice) project ever, so I'm not sure where all the data would be harvested from.  We've been bitten by the Sphinx plugin because we're using resources instead of services, and maybe our choice to use resources here will also bite us.   

For example, i see that there exists `service.description`, but how can we ever set this value through our resource?  I've resorted to placing the description in the `@resource` decorated class docstring.  _description_ is part of a [_Tag Object_](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#tagObject). 

Also, where are global _parameters_ and _responses_ defined with cornice?  _validation_ rules? I'm trying to find out how to find data types from cornice/pyramid, especially if they are used by many _operations_ (ie nearly every operation must send an authentication token in the header: Swagger lets us define this at either the _Swagger Object_ or _parameters_ level as globals for Operations to refer to.  

Lastly, we may have some cross talk because I'm implementing for Swagger 2.0 and your gist is for Swagger 1.2.

**Comment by leplatrem** [comment]
Since @delijati built a swagger extension here: https://github.com/Cornices/cornice.ext.swagger I am tempted to close this bug... There might some parts of your feedback that may be worth discussing there directly, if you're still interested.

Thanks again for your detailed feedback, I'm sorry if you got bitten by this resource black magic.

Regarding the `@resource` feature, we had discussed about deprecating it in the past, but we first must open a discussion to see where it can lead. I'll spawn an issue.
