### ISSUE TITLE
marshmallow (de)serialization

### ISSUE THREAD

**Issue by philtay** [Cornices/cornice#274]
Are you interested in adding support for [marshmallow](https://github.com/marshmallow-code/marshmallow) in cornice? marshmallow is a (de)serialization library and I think it would be really good to have it integrated in cornice (alongside or even instead of colander). I can open a PR for this if you wish.

**Comment by ametaireau** [comment]
I would be happy to have something in cornice that let you use whatever deserialisation mechanism.

I believe it's already the case and it would be pretty easy to add validation logic that uses marshmallow rather than colander. If it's not the case, we should of course make cornice evolve to support that.

**Comment by leplatrem** [comment]
With cornice 2.0 (current master), it'll be very easy to plug marshmallow (cf. #397)
