### ISSUE TITLE
route_prefix usage isn't clear

### ISSUE THREAD

**Issue by tisdall** [Cornices/cornice#304]
I've read the docs and looked through the code and I still have no idea how to use the `route_prefix` functionality.  I managed to get something to work by doing the following in the `main()`:
```
    config.route_prefix = '/api'
    config.include("cornice")
```

The Pyramid docs explain that it should be something like:
```
    config.include("cornice", route_prefix='/api')
```

... but that simply doesn't work.  But I can't really see _why_ it doesn't work from the code either.

The docs say something about a Cornice configuration ini?  No explanation as to how that works, though.

**Comment by ametaireau** [comment]
Hi!

Cornice doesn't do anything fancy about `route_prefix`. To be able to help you out properly, I would need to see your code or a test case which points at what's not working.

I think the `route_prefix` is correct in what you're doing. You can have a look at how we use it in cliquet for more information: https://github.com/mozilla-services/cliquet/blob/master/cliquet/initialization.py#L337

**Comment by tisdall** [comment]
In cliquet, it looks like you're doing `config.route_prefix = ` as well.  I suspect the `route_prefix=api_version` in the `include()` isn't doing anything.

**Comment by ametaireau** [comment]
It does, but if you're including again some other configurations, it might make sense to pass it along, or not, depending what you're doing. https://github.com/Pylons/pyramid/blob/dddf33c6b9558fbfdb1bc048b6371e87ddc4388b/pyramid/config/__init__.py#L247-L249

**Comment by tisdall** [comment]
Okay, maybe I'm just not understanding how it's supposed to work.  I don't seem to see any functional difference between `config.include("cornice", route_prefix='/api')` and `config.include("cornice")`.  All routes added by cornice have no prefix added to them in either case.

I think it may be due to the `config` being used isn't the one with the modified `route_prefix` passed into the `includeme`, but rather the global one used with the venusian callback.

**Comment by memee** [comment]
For me it's not clear as well. I try with `config.include("cornice", route_prefix='/v1')` and it makes no difference.

**Comment by tisdall** [comment]
@memee - yeah, I'm pretty sure it's a bug.  You can do `config.route_prefix = '/v1'` as a work around, but unfortunately it'll apply to all views defined after that.

**Comment by dairiki** [comment]
I think it works as intended.

The `cornice` package itself does not define any routes, which is why `config.include("cornice", route_prefix='/v1')` does nothing.  The `route_prefix` only has an effect if the included package defines routes.

As a contrived example, suppose `mypkg/__init__.py` contains:
```
def includeme(config):
    config.include('cornice')
    config.scan('mypkg.foo')
```
and `mpkg/foo.py` looks something like
```
from cornice.resource import resource

@resource(
    path='/foos/{id}.json',
    collection_path='/foos.json',
    ...)
class FooResource(object)
    ...
```
Note that calling `config.include('mypkg')` will define the routes `/foos.json` and `/foos/{id}.json`.
Calling `config.include('mypkg', route_prefix='/api/v1')` will instead define the prefixed routes, `/api/v1/foos.json` and `/api/v1/foos/{id}.json`.

**Comment by tisdall** [comment]
@dairiki - ah.. that clears things up!  I knew the issue was the `config` that was being used to add the cornice "stuff" (in the includeme) wasn't the same one passed into the venusian callback and thus it didn't work.

**Comment by tisdall** [comment]
@dairiki - I just tried what you suggested but there seems to be an issue...  If you do `config.include('mypkg', route_prefix='/api/v1')` followed by `config.scan()` (needed to scan for the other views in my application) the views registered by the `config.scan('mypkg.foo')` are overwritten.  In order to complete the example, you need to do:
```python
    config.include('mypkg', route_prefix='/api/v1')
    config.scan(ignore='mypkg')
```

**Comment by dairiki** [comment]
@tisdall Yes, that makes sense.  Generally I would expect that `mypkg`’s `includeme` should be doing the scanning of `mypkg` (in which case, the `route_prefix` will “take”.)  As you note, if `mypkg` is scanned again after that, its routes will be overwritten by versions without the `route_prefix`.
When `include`ing an external package, this is not an issue, since the `scan` only finds submodules and subpackages.  Otherwise one needs to be careful about what modules are scanned — either by using `ignore=`, as you did, or by being explicit about which packages and/or modules you *do* want to scan.  I usually go the latter route, since, for me, it leads to fewer surprises.  E.g.
```
    config.include('.mysubpkg', route_prefix='/api/v1')
    config.scan('.views')
    config.scan('.subscribers')
```

**Comment by tisdall** [comment]
@dairiki - Are you saying that in the sub-package's `includeme` you can get away with just doing `config.scan()` and it will only scan itself and it's sub-directories?

**Comment by dairiki** [comment]
@tisdall Yes, I'm pretty sure that's correct. The [pyramid docs](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.scan) say

> scan(package=None, categories=None, onerror=None, ignore=None, **kw)
>
> Scan a Python package and any of its subpackages for objects marked with configuration decoration such as pyramid.view.view_config. Any decorated object found will influence the current configuration state.
> 
> The *package* argument should be a Python package or module object (or a dotted Python name which refers to such a package or module). **If *package* is `None`, the package of the caller is used.**

**Comment by diogogeru** [comment]
> @dairiki - Are you saying that in the sub-package's `includeme` you can get away with just doing `config.scan()` and it will only scan itself and it's sub-directories?

This discussion helped me A LOT. Thanks.
