### ISSUE TITLE
Default Validator for Malformed JSON?

### ISSUE THREAD

**Issue by mazz** [Cornices/cornice#445]
Question:

In Cornice, is there a default validator/filter that will check if the JSON is malformed in the Request.json_body? Is that implemented by doing:

```
def includeme(config):
    DEFAULT_FILTERS.append(your_callable)
```

If I set the content_type to "application/json" then do I get error-handling of malformed JSON "for free"?:

```
@service.post(content_type="application/json")
def foo(request):
    return 'Foo'
```

Or is there something specific I need to do for malformed JSON?

**Comment by leplatrem** [comment]
This sounds like a very reasonable use-case!

Instead of a direct mutation of `DEFAULT_FILTERS` or `DEFAULT_VALIDATORS`, I would suggest to inherit the Service class instead. *(I know it's what is mentioned in the docs, maybe it's a matter of taste)*

```python
class JsonService(cornice.Service):
    default_validators = [validate_json]
```

>  do I get error-handling of malformed JSON "for free"?

Unfortunately nope, there's no implicit validator like that.

I think we can really improve the developer experience here. If you're interested in contributing something, let us know we can find something out to fix that!

Thanks for your feedback!

**Comment by mazz** [comment]
@leplatrem I tried implementing 

```
@service.post(content_type="application/json")
def foo(request):
    return 'Foo'
```

and 

```
@service.post(content_type="application/json", require_csrf=false)
def foo(request):
    return 'Foo'
```

and in both cases I get back "invalid CSRF Token" -- there must be something wrong?

**Comment by leplatrem** [comment]
Do you use the last version of Cornice? 'cuz there is no notion of CSRF token in the code ;)

**Comment by FaithfulAudio** [comment]
My apologies, I might still be on 2.3.0. I will try and upgrade.

**Comment by leplatrem** [comment]
@mazz @FaithfulAudio any progress?

**Comment by mazz** [comment]
@leplatrem yes, the thing was I was returning HTTPOk(responsedict) and that was overriding the Content-Type to text/html. Once I removed HTTPOk() I was getting back the expected application/json.

The CSRF token check seems to be something Pyramid does by default on .post() calls. I can't tell if there is a way to disable the check other than explicitly using `require_csrf=false`

Once I did the above plus upgrade to Cornice 2.4.0, everything works as expected. Thanks for follwoing up.
