### ISSUE TITLE
Why was traversal parameter support removed?

### ISSUE THREAD

**Issue by dz0ny** [Cornices/cornice#483]
I have seen https://github.com/Cornices/cornice/issues/179#issuecomment-23774650 but later versions added support for traverse parameter, however 3.2 removed support? Was it for performance reasons or something else? I've see `colander_path_validator` but that has different use case...

**Comment by leplatrem** [comment]
Good question!

I arrived late in the Cornice project, and @tarekziade and @almet always let me assume that *traversal* was not supported. 

Since I never considered it supported, its removal in 3.2 should be a side-effect and not intentional!

If you're interested, we can restore it, and the best for that would be that you contribute a small example setup as a test suite so that it becomes part of the expected features :)

Thanks for your feedback!

**Comment by ergo** [comment]
@dz0ny Recent cornice can accept `pyramid_route` parameter on services utilising existing pyramid routes instead of creating fresh ones with service decorators.

Like this: https://github.com/Cornices/cornice/blob/master/tests/test_pyramidhook.py#L283

Would that solve your problem?

**Comment by karantan** [comment]
>  If you're interested, we can restore it, and the best for that would be that you contribute a small example setup as a test suite so that it becomes part of the expected features :)

@leplatrem I've created a PR for this.

**Comment by karantan** [comment]
I think we can close this.
